jobs:
- job: generator  
  steps:
  - task: GitVersion@5
    inputs:
      runtime: 'core'
      useConfigFile: true
      configFilePath: 'GitVersion.yml'
  - task: CmdLine@2
    inputs:
      script: 'dotnet gitversion'
