jobs:
- job: Linux
  steps:
  - bash: mono --version
    name: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
- job: macOS
  steps:
  - bash: mono --version
    name: macOS
  pool:
    vmImage: 'macOS-latest'