variables: { DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true', DOTNET_CLI_TELEMETRY_OPTOUT: 'true' }

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps: 
  - task: CmdLine@2
    inputs:
      script: 'dotnet --info'
  - task: CmdLine@2
    inputs:
      script: dotnet tool install gitversion.tool --tool-path gtool
  - task: CmdLine@2  
    inputs:
      script: |
        export DOTNET_ROOT="$(dirname "$(readlink "$(command -v dotnet)")")"
        echo $DOTNET_ROOT
        gtool/dotnet-gitversion
  # - task: CmdLine@2
  #   inputs:
  #     script: 'dotnet tool install gitversion.tool --tool-path gtool'

  # - task: GitVersion@5
  #   inputs:
  #     versionSpec: '5.0.x'
  #     includePrerelease: true
