variables: { DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true', DOTNET_CLI_TELEMETRY_OPTOUT: 'true' }

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps: 
  # - task: CmdLine@2
  #   inputs:
  #     script: 'dotnet --info'
  # - task: CmdLine@2
  #   inputs:
  #     script: dotnet tool install gitversion.tool --tool-path gtool
  # - task: CmdLine@2  
  #   inputs:
  #     script: |
  #       export DOTNET_ROOT="$(dirname "$(readlink "$(command -v dotnet)")")"
  #       gtool/dotnet-gitversion
  # - task: CmdLine@2
  #   inputs:
  #     script: 'dotnet tool install gitversion.tool --tool-path gtool'

  # - task: GitVersion@5
  #   inputs:
  #     versionSpec: '>5.0.2-beta1'
  #     includePrerelease: true
  
  - task: SetupGitVersion@5
    inputs:
      versionSpec: '5.1.2'
  - task: ExecuteGitVersion@5
    name: gitversion
  - bash: echo $fullSemVer