jobs:
- job: Linux
  steps:
  - bash: mono --version
    name: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
- job: macOS
  steps:
  - task: CmdLine@2
    condition: eq( variables['Agent.OS'], 'Darwin' )
    displayName: 'Select Mono version'
    inputs:
      script: |
        SYMLINK=5_18_1
        MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
        echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
        echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
        echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
  - bash: mono --version
    name: macOS
  pool:
    vmImage: 'macOS-latest'